server {
    listen 80;
    server_name 176.108.249.27;
    client_max_body_size 500M;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://carouselbackend:5087/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_cookie_domain ~^(.*)$ "176.108.249.27";
        proxy_cookie_path / "/;";
        proxy_pass_header Set-Cookie;
        proxy_set_header Cookie $http_cookie;
        
        add_header Access-Control-Allow-Credentials "true";
        add_header Access-Control-Expose-Headers "Set-Cookie";
    }

    # Прокси для изображений (соответствует app.use('/images', ...))
    location /images/ {
        proxy_pass http://carouselbackend:5087/images/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Отключаем кэширование как в Express
        add_header Cache-Control "no-store";
        expires off;
    }
    
    # Дополнительно: если нужны другие статические файлы из public
    location ~ ^/(css|js|fonts|public)/ {
        proxy_pass http://carouselbackend:5087;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}