server {
    listen 80;
    server_name 176.108.249.27;
    client_max_body_size 500M;
    
    # MIME-типы для статики React
    types {
        text/html html htm;
        text/css css;
        application/javascript js;
        image/webp webp;
        image/jpeg jpg jpeg;
        image/png png;
        image/gif gif;
    }
    
    # Статика React (CSS, JS, HTML)
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    
    # Изображения - прокси на Express
    location /images/ {
        proxy_pass http://carouselbackend:5087/images/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Явно указываем тип для правильного отображения
        proxy_hide_header Content-Type;
        add_header Content-Type image/webp always;
    }
    
    # API - прокси на Express
    location /api/ {
        proxy_pass http://carouselbackend:5087/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Для кук
        proxy_cookie_domain ~^(.*)$ "176.108.249.27";
        proxy_cookie_path / "/;";
        proxy_pass_header Set-Cookie;
        proxy_set_header Cookie $http_cookie;
        
        add_header Access-Control-Allow-Credentials "true";
        add_header Access-Control-Expose-Headers "Set-Cookie";
    }
}