services:
  carouselbackend:
    build: ./carouselbackend
    ports:
      - "5087:5087"  # Изменяем внешний порт на 8001
    environment:
      - DATABASE_URL=postgresql://postgres:PasswordDBWEB2025&@176.108.249.27:5432/psycho
 #      - UPLOAD_DIR=/app/uploads  # Добавьте эту переменную
      - DOCKER_CONTAINER=true  # Добавьте эту переменную
    volumes:
      - ./carouselbackend/public/images:/app/public/images

  carouselfrotend:
    build: ./carouselfrotend
    ports:
      - "5077:80"  # Изменяем внешний порт фронтенда на 8080
      - "5075:443"
    depends_on:
      - carouselbackend
  #     - express

  # caruselbackend:
  #   build:
  #     context: ./comics-carousel
  #     dockerfile: Dockerfile.backend
  #   container_name: comics_backend
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - PORT=3001
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://postgres:PasswordDBWEB2025&@176.108.249.27:5432/database_comics
  #   restart: unless-stopped

  # caruselfrontend:
  #   build:
  #     context: ./comics-carousel
  #     dockerfile: Dockerfile.frontend
  #   container_name: comics_frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - caruselbackend
  #   restart: unless-stopped